import {StyleSheet} from 'react-native';
export default (Styles = StyleSheet.create({
  ViewContentDescription: {
    backgroundColor: '#ddd2',
    position: 'absolute',
    top: '100%',
  },
  InternalOptionMenu: {
    position: 'absolute',
    right: 0,
    top: 0,
  },
  InternalOptionMenuButton: {
    alignContent: 'flex-end',
    backgroundColor: '#0001',
    paddingLeft: '2%',
    paddingBottom: '2%',
    borderBottomLeftRadius: 8,
  },
  topLayout: {
    backgroundColor: '#ff8636',
    paddingBottom: 10,
  },

  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  userPicture: {
    borderColor: '#0008',
    borderWidth: 1,
    resizeMode: 'cover',
    width: '28%',
    height: '28%',
    borderRadius: 100,
    margin: '3%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userNameText: {
    color: 'white',
    fontSize: 3,
    fontFamily: 'Chewy-Regular',
    paddingLeft: '2%',
  },
  userInfoText: {
    color: 'white',
    fontSize: 2,
    fontFamily: 'Chewy-Regular',
    paddingLeft: '2%',
  },
  view1: {
    flexDirection: 'row',
    backgroundColor: '#ff8636',
  },
  petName: {
    fontSize: 5,
   
  },
  listItem: {
    aspectRatio: 1.5,
    flexDirection: 'row',
    marginBottom: 5,
    padding: 2,
    borderColor: '#444',
    borderWidth: 1,
    borderRadius: 2,
  },
  picture: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    overflow: 'hidden',
  },
  textStatus: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
    transform: [{translateY: '5%'}],
    color: '#e00',
  },
  button: {
    height: 42,
    backgroundColor: '#f05a5b',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    marginTop: 15,
  },
  buttonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  InternBodyCard: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderBottomColor: 'rgba(0,0,0,0.05)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    width: '33%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  InternTextCard: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    borderBottomColor: 'rgba(0,0,0,0.05)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    width: '33%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerCard: {
    width: '100%',
    height: '120%',
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#CCC',
    flexWrap: 'nowrap',
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: {
      width: -2,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 1.5,
    elevation: 3,
    overflow: 'hidden',
  },
  cardItemImagePlaceCard: {
    backgroundColor: '#ccc',
    width: '100%',
    height:'100%',
  },
  cardBodyCard: {
    position: 'absolute',
    top: '86%',
    backgroundColor: 'rgba(0,0,0,0.2)',
    left: 0,
    right: 0,
    height: '14%',
  },
  titleStyleCard: {
    fontSize: 24,
    color: '#FFF',
    paddingBottom: 12,
  },
  subtitleStyleCard: {
    fontSize: 14,
    color: '#000',
    lineHeight: 16,
    opacity: 0.5,
    borderRadius: 30,
  },
  actionButton1Card: {
    padding: 8,
    height: 36,
  },
}));
